eval: add a rewrite module to handle queries with namespaces.
Netflix/atlas pull request #1675
Opened 2024-07-30 04:07 UTC by manolama

DataSource URIs are sent via HTTP (with retries) and if they incorporate namespace predicates, the service will rewrite them to route to the proper host, removing the namespace predicate.

2024-07-30 13:14 UTC, brharrington requested changes

2024-07-30 13:14 UTC, brharrington commented on atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/NamespaceRewriter.scala
> +        case Failure(ex) =>
This is typically handled with settings on the pool:

https://pekko.apache.org/docs/pekko-http/current/client-side/host-level.html#retrying-a-request

2024-07-30 13:14 UTC, brharrington commented on atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/NamespaceRewriter.scala
> +    val uri = config.getString("rewriteUrl")
This should be prefixed. For HOCON hyphen separated is the recommendation:

https://github.com/lightbend/config/blob/main/HOCON.md#hyphen-separated-vs-camelcase

2024-07-30 13:14 UTC, brharrington commented on atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/NamespaceRewriter.scala
> +class NamespaceRewriter(config: Config, implicit val system: ActorSystem) extends StrictLogging {
In theory we could use it for other things, not sure it should be specific to namespaces. It is just an endpoint we use to perform a rewrite on the URIs.

2024-07-30 18:22 UTC, manolama commented on atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/EvaluatorImpl.scala
> +      .mapAsync(1)(namespaceRewriter.rewriteNamespaces)
I'll give that a try.

2024-07-30 18:22 UTC, manolama commented on atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/NamespaceRewriter.scala
> +        foreachField(parser) {
I was worried about huge lists of URIs but we'll likely only have one or two at a time so a class would be fine.

2024-07-30 18:23 UTC, manolama commented on atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/NamespaceRewriter.scala
> +            if (status.toUpperCase() == "OK") {
It is, just being defensive for the future.

2024-07-30 19:04 UTC, manolama commented on atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/NamespaceRewriter.scala
> +            new IllegalArgumentException(s"Failed to rewrite URI $original, message: $msg")
Drats, right.

2024-07-30 19:04 UTC, manolama commented on atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/NamespaceRewriter.scala
> +        case Failure(ex) =>
Ah that's how to do it, thanks.

2024-07-30 19:06 UTC, manolama commented on atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/NamespaceRewriter.scala
> +    val uri = config.getString("rewriteUrl")
It is prefixed with `atlas.eval.graph` but it's stripped out by `EvaluatorImpl`

2024-07-30 19:06 UTC, manolama commented on atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/NamespaceRewriter.scala
> +class NamespaceRewriter(config: Config, implicit val system: ActorSystem) extends StrictLogging {
ack

2024-07-30 23:05 UTC, brharrington commented on atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/NamespaceRewriter.scala
> +        foreachField(parser) {
It might be thousands in some cases, but still I don't think this would be the hot spot and clarity and maintainability are probably better tradeoffs here.

2024-07-30 23:11 UTC, brharrington commented on atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/NamespaceRewriter.scala
> +        case Failure(ex) =>
#1677 updates the helper to have a flow option and instrument it better.

I'll have to think about the degradation a bit. Will need to ensure that the rewrite call failing overall will have no impact other than preventing data source changes and that those would get picked up automatically when it recovers.

2024-08-01 18:43 UTC, manolama commented on atlas-eval/src/main/scala/com/netflix/atlas/eval/stream/NamespaceRewriter.scala
> +        case Failure(ex) =>
Caching the rewrites for a reconnect? That's the only time we'd need to worry about it right? Otherwise if a new eval was submitted the caller would need to retry.

2024-08-20 20:10 UTC, brharrington approved these changes

2024-08-20 20:11 UTC, merged